require_relative 'figure'
require_relative 'knight'
require_relative 'king'
require_relative 'rook'
require_relative 'bishop'
#print Knight.new("g2").possible_moves
#print King.new("g2").possible_moves
#print Rook.new("g2").possible_moves
#print Bishop.new("g2").possible_moves
