require_relative 'figure'
require_relative 'knight'
require_relative 'king'
require_relative 'rook'
require_relative 'bishop'
#require_relative 'pawn'
#require_relative 'queen'
#print Knight.new("g2").possible_moves
#print King.new("g2").possible_moves
#print Rook.new("g2").possible_moves
#print Bishop.new("g2").possible_moves
#print Pawn.new("g2").possible_moves
#print Queen.new("g2").possible_moves
